export const DEX_DEFAULT_NAME = 'Swaptoshi';
export const DEX_DEFAULT_TOKEN_SYMBOL = 'DEX';
export const DEX_DEFAULT_TOKEN_DECIMAL = 8;

export const MAINCHAIN_DEFAULT_TOKEN_SYMBOL = 'LSK';
export const MAINCHAIN_DEFAULT_TOKEN_DECIMAL = 8;
